
package com.mycompany.practica5diu;

import java.awt.event.ItemEvent;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marti
 */
public class Practica5 extends javax.swing.JFrame {
    private boolean rojo=true;
    private boolean verde=true;
    private boolean azul=true;
    public Practica5() {
        initComponents();
        setLocationRelativeTo(null);
        todosCheckBox.setSelected(true);
        azulCheckBox.setSelected(true);
        rojoCheckBox.setSelected(true);
        verdeCheckBox.setSelected(true);
        avisoLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        todosCheckBox = new javax.swing.JCheckBox();
        rojoCheckBox = new javax.swing.JCheckBox();
        verdeCheckBox = new javax.swing.JCheckBox();
        azulCheckBox = new javax.swing.JCheckBox();
        tituloLabel = new javax.swing.JLabel();
        canalesInfoLabel = new javax.swing.JLabel();
        esquinaLabel = new javax.swing.JLabel();
        supDerechaRad = new javax.swing.JRadioButton();
        supIzquierdaRad = new javax.swing.JRadioButton();
        infIzquierdaRad = new javax.swing.JRadioButton();
        infDerechaRad = new javax.swing.JRadioButton();
        lienzoImg1 = new com.mycompany.practica5diu.LienzoImg();
        avisoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        todosCheckBox.setText("Todos");
        todosCheckBox.setToolTipText("Todos los canales RGB visibles");
        todosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosCheckBoxActionPerformed(evt);
            }
        });

        rojoCheckBox.setText("Rojo");
        rojoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rojoCheckBoxActionPerformed(evt);
            }
        });

        verdeCheckBox.setText("Verde");
        verdeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdeCheckBoxActionPerformed(evt);
            }
        });

        azulCheckBox.setSelected(true);
        azulCheckBox.setText("Azul");
        azulCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azulCheckBoxActionPerformed(evt);
            }
        });

        tituloLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tituloLabel.setText("Filtro RGB de imagen");

        canalesInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        canalesInfoLabel.setText("Selecciona los canales visibles:");
        canalesInfoLabel.setToolTipText("Canales de color activos en la imagen");

        esquinaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        esquinaLabel.setText("Elige la esquina del logo:");
        esquinaLabel.setToolTipText("Esquina donde estará el logo");

        buttonGroup1.add(supDerechaRad);
        supDerechaRad.setSelected(true);
        supDerechaRad.setText("Superior derecha");
        supDerechaRad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supDerechaRadItemStateChanged(evt);
            }
        });

        buttonGroup1.add(supIzquierdaRad);
        supIzquierdaRad.setText("Superior  izquierda");
        supIzquierdaRad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supIzquierdaRadItemStateChanged(evt);
            }
        });

        buttonGroup1.add(infIzquierdaRad);
        infIzquierdaRad.setText("Inferior izquierda");
        infIzquierdaRad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                infIzquierdaRadItemStateChanged(evt);
            }
        });

        buttonGroup1.add(infDerechaRad);
        infDerechaRad.setText("Inferior derecha");
        infDerechaRad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                infDerechaRadItemStateChanged(evt);
            }
        });

        lienzoImg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lienzoImg1.setPreferredSize(new java.awt.Dimension(425, 371));

        javax.swing.GroupLayout lienzoImg1Layout = new javax.swing.GroupLayout(lienzoImg1);
        lienzoImg1.setLayout(lienzoImg1Layout);
        lienzoImg1Layout.setHorizontalGroup(
            lienzoImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        lienzoImg1Layout.setVerticalGroup(
            lienzoImg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        avisoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        avisoLabel.setText("¡No puedes desactivar todos!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(tituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esquinaLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infIzquierdaRad)
                            .addComponent(supDerechaRad)
                            .addComponent(supIzquierdaRad)
                            .addComponent(infDerechaRad)))
                    .addComponent(canalesInfoLabel)
                    .addComponent(todosCheckBox)
                    .addComponent(rojoCheckBox)
                    .addComponent(verdeCheckBox)
                    .addComponent(azulCheckBox)
                    .addComponent(avisoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(lienzoImg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(canalesInfoLabel)
                        .addGap(7, 7, 7)
                        .addComponent(todosCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rojoCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verdeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(azulCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(avisoLabel)
                        .addGap(33, 33, 33)
                        .addComponent(esquinaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supDerechaRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infDerechaRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infIzquierdaRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supIzquierdaRad)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(lienzoImg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void todosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosCheckBoxActionPerformed
        if(todosCheckBox.isSelected()){
            avisoLabel.setVisible(false);
            verdeCheckBox.setSelected(true);
            rojoCheckBox.setSelected(true);
            azulCheckBox.setSelected(true);
            rojo=true;
            verde=true;
            azul=true;
            lienzoImg1.changeRGB(rojo,verde,azul);
            repaint();
        }
    }//GEN-LAST:event_todosCheckBoxActionPerformed

    private void rojoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rojoCheckBoxActionPerformed
        if(verde==false&&azul==false){
            rojoCheckBox.setSelected(true);
            avisoLabel.setVisible(true);
        }
        if(rojoCheckBox.isSelected()==false){
            //avisoLabel.setVisible(false);
            todosCheckBox.setSelected(false);
            rojo=false;
            lienzoImg1.changeRGB(rojo,verde,azul);
            repaint();
        }else{
            if(azul==true||verde==true){
                avisoLabel.setVisible(false);
            }
            rojo=true;
            lienzoImg1.changeRGB(rojo,verde,azul);
            repaint();
        }
    }//GEN-LAST:event_rojoCheckBoxActionPerformed

    private void verdeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdeCheckBoxActionPerformed
        if(rojo==false&&azul==false){
            verdeCheckBox.setSelected(true);
            avisoLabel.setVisible(true);
        }
        if(verdeCheckBox.isSelected()==false){
            //avisoLabel.setVisible(false);
            todosCheckBox.setSelected(false);
            verde=false;
            lienzoImg1.changeRGB(rojo,verde,azul);
            repaint();
        }else{
            if(azul==true||rojo==true){
                avisoLabel.setVisible(false);
            }
            verde=true;
            lienzoImg1.changeRGB(rojo,verde,azul);
            repaint();
        }
        
    }//GEN-LAST:event_verdeCheckBoxActionPerformed

    private void azulCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azulCheckBoxActionPerformed
        if(verde==false&&rojo==false){
            azulCheckBox.setSelected(true);
            avisoLabel.setVisible(true);
        }
        if(azulCheckBox.isSelected()==false){
            //avisoLabel.setVisible(false);
            todosCheckBox.setSelected(false);
            azul=false;
            lienzoImg1.changeRGB(rojo,verde,azul);
            repaint();
        }else{
            if(rojo==true||verde==true){
                avisoLabel.setVisible(false);
            }
            azul=true;
            lienzoImg1.changeRGB(rojo,verde,azul);
            repaint();
        }
    }//GEN-LAST:event_azulCheckBoxActionPerformed

    private void supDerechaRadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supDerechaRadItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            lienzoImg1.posLogo("Right-Up");
            repaint();
        }
        
    }//GEN-LAST:event_supDerechaRadItemStateChanged

    private void supIzquierdaRadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supIzquierdaRadItemStateChanged
       if(evt.getStateChange()==ItemEvent.SELECTED){
            lienzoImg1.posLogo("Left-Up");
            repaint();
        }
    }//GEN-LAST:event_supIzquierdaRadItemStateChanged

    private void infIzquierdaRadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_infIzquierdaRadItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            lienzoImg1.posLogo("Left-Down");
            repaint();
        }
    }//GEN-LAST:event_infIzquierdaRadItemStateChanged

    private void infDerechaRadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_infDerechaRadItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            lienzoImg1.posLogo("Right-Down");
            repaint();
        }
    }//GEN-LAST:event_infDerechaRadItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JCheckBox azulCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel canalesInfoLabel;
    private javax.swing.JLabel esquinaLabel;
    private javax.swing.JRadioButton infDerechaRad;
    private javax.swing.JRadioButton infIzquierdaRad;
    private com.mycompany.practica5diu.LienzoImg lienzoImg1;
    private javax.swing.JCheckBox rojoCheckBox;
    private javax.swing.JRadioButton supDerechaRad;
    private javax.swing.JRadioButton supIzquierdaRad;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JCheckBox todosCheckBox;
    private javax.swing.JCheckBox verdeCheckBox;
    // End of variables declaration//GEN-END:variables
}
